// <auto-generated />
namespace WarframeResDemo.EFr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5));
        
        string IMigrationMetadata.Id
        {
            get { return "202001100938218_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
