// <auto-generated />
namespace WarframeResDemo.EFr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6));
        
        string IMigrationMetadata.Id
        {
            get { return "202001181531325_6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
